steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/calm-vertex-477916-c4/medusa/medusa',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/calm-vertex-477916-c4/medusa/medusa'
      ]

images:
  - 'us-central1-docker.pkg.dev/calm-vertex-477916-c4/medusa/medusa'
