import { defineJoinerConfig, Modules } from "@medusajs/framework/utils"
import Product from "#models/product"
import ProductCategory from "#models/product-category"
import ProductCollection from "#models/product-collection"
import ProductImage from "#models/product-image"
import ProductOption from "#models/product-option"
import ProductOptionValue from "#models/product-option-value"
import ProductTag from "#models/product-tag"
import ProductType from "#models/product-type"
import ProductVariant from "#models/product-variant"
import { default as schema } from "#schema/index"

export const joinerConfig = defineJoinerConfig(Modules.PRODUCT, {
  schema,
  models: [
    Product,
    ProductVariant,
    ProductOption,
    ProductOptionValue,
    ProductType,
    ProductTag,
    ProductCollection,
    ProductCategory,
    ProductImage,
  ],
  linkableKeys: {
    // Merged with the autogenerated ones to maintain backward compatibility
    variant_id: "ProductVariant",
  },
  primaryKeys: ["id", "handle"],
  alias: [
    {
      name: ["product_variant", "product_variants", "variant", "variants"],
      entity: "ProductVariant",
      args: {
        methodSuffix: "ProductVariants",
      },
    },
  ],
})
